### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FreakyFishThing** [laurencedawson/sync-for-reddit#372] opened 2020-09-19 00:56 UTC
**Describe the bug**
When going to change flair in a subreddit, only one option appears listing instead of a list of flairs the subreddit offers

**To Reproduce**
1. Go to any subreddit
2. Click on sidebar
3. Tap the 3 dots at the top right
4. Tap "flair"
5. See error

**Expected behavior**
Before, and in other reddit apps, a list of flairs would become available to choose from

**Screenshots**
![Screenshot_20200919-014332](https://user-images.githubusercontent.com/71534107/93655394-e79ad880-fa1a-11ea-86f0-c9965a87fe33.jpg)
![Screenshot_20200919-014304](https://user-images.githubusercontent.com/71534107/93655402-f4b7c780-fa1a-11ea-8a06-d6409a20fc60.jpg)
Screenshot 1 is from Sync while screenshot 2 is from the official app, both are from the same subreddit

**Smartphone (please complete the following information):**
 - Device: [Oneplus 6t]
 - OS: [Android 10/OxygenOS 10.3.5] 
 - Browser: [Brave]
 - Version: [Beta 19]

**Additional context**
I haven't always had this issue, it's been on and off.

**Comment by hmzuleta** [comment] 2020-09-21 10:37
Duplicate of #371

**Closed** 2020-11-22 21:15 UTC
Labels: bug
