### ISSUE TITLE
[BUG] "No messages returned" banner doesn't disapper automatically

### ISSUE THREAD

**Issue by NickPfeiffer** [laurencedawson/sync-for-reddit#234] opened 2020-06-10 18:12 UTC
**Describe the bug**
The "No messages returned" banner that is displayed at the bottom when you have no unread messages doesn't disapper automatically and needs to be swiped away

**To Reproduce**
1. Go to 'Messages'
2. Change to 'Inbox unread'
3. Mark all as read if you have unread messages
4. "No messages returned" banner appears
5. Go to 'Posts'
6. Banner is still there

**Expected behavior**
The banner automatically disapperas after a few seconds or also has a "Dismiss" text on it or the "Messages" view just shows a text with "No unread messages"

**Screenshots**
[pic](https://i.imgur.com/V6fuVOB.jpg)

**Smartphone (please complete the following information):**
- Device: OnePlus 7 Pro
- OS: Android 10, Oxygen 10.0.6
- Browser: DuckDuckGo 5.55.1
- Version: vv20 (beta 4)

**Additional context**
The color of the banner should maybe also be changed from being white/light grey to something darker for dark mode (not sure about Material Design Guidelines on this thing though)

**Comment by hmzuleta** [comment] 2020-06-27 04:43
My [bug submission](https://github.com/laurencedawson/sync-for-reddit/issues/271)  might be a duplicate of yours. I can confirm this happens.

**Comment by NickPfeiffer** [comment] 2020-06-28 15:24
@hmzuleta Yes, only that your description of the bug sounds almost unrelated to the bug in my opinion. But the bug is the same, so yours is indeed a duplicate, but the video could be useful.

**Comment by hmzuleta** [comment] 2020-06-28 22:01
[Here's the video](https://i.imgur.com/WGufJdz.mp4), in case my duplicate Bug report gets closed.

**Comment by hmzuleta** [comment] 2020-07-02 04:47
Can confirm this still happens in beta 7.

**Comment by laurencedawson** [comment] 2021-01-15 19:43
This has since been fixed.

**Closed by laurencedawson** 2021-01-15 19:43 UTC
Labels: bug
