### ISSUE TITLE
[BUG] Share intent bug

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/sync-for-reddit#581] opened 2021-02-16 23:48 UTC
From this post: https://www.reddit.com/r/redditsync/comments/ljuzel/request_sharedr_integration/

This is the feedback the ShareDR-team asked me to share:

Bug: Share intent should use setClipData(uri) for content:// uris  

Sharing an image doesn't show a preview on the system share sheet on Android 10+. This also causes a problem when I use a 3rd party share replacement app like Sharedr (https://sharedr.rejh.nl) when sharing any type of file. It's likely that the app does not call setClipData() on the intent but only provides EXTRA_STREAM which doesn't properly grant the read permissions on the uri.

Please refer to this bug on the AOSP bug tracker for more information: https://issuetracker.google.com/issues/176280829

**Comment by laurencedawson** [comment] 2021-02-20 14:13
I tried the example code linked and sharedr still failed to show a thumbnail..

Worse still their example code crashed their own app. Closing.

**Comment by laurencedawson** [comment] 2021-02-28 22:39
This only applies to sharing from the saved image notification. Re-opening.

**Comment by rejhgadellaa** [comment] 2021-03-02 17:38
Hi, I'm the developer of Sharedr. Thanks for taking the time to look into this.

> I tried the example code linked and sharedr still failed to show a thumbnail..

Sharedr doesn't show a thumbnail of a shared image. The system share menu does (if it can access the file, which it doesn't seem to be able to). It will grant the receiving app the read permissions but not to itself. It's complicated, see https://issuetracker.google.com/issues/176280829

> Worse still their example code crashed their own app.

That's.. interesting. Any chance you noticed which error/exception caused the crash? I would assume Security or Bad Parcable Exception?

Again, thanks for looking into this. If I can help, let me know!

**Comment by laurencedawson** [comment] 2021-03-31 21:58
@rejhgadellaa sorry but I was unable to reproduce the crash after. Odd.

Closing as I've added the additional flag Intent.FLAG_GRANT_READ_URI_PERMISSION which should resolve the issue.

**Closed by laurencedawson** 2021-03-31 21:58 UTC
Labels: bug, wontfix
