### ISSUE TITLE
[BUG] Subs favorited without an account disappear after app close

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-reddit#299] opened 2020-07-04 01:14 UTC
**Describe the bug**
The list of subs added to the favorites list disappear after the app closes if not tied to a Reddit account.

**To Reproduce**
1. Open app without logging into Reddit account
2. Go to a sub, like _r/redditsync_
3. Open sub sidebar and click Favorite
4. Open subs tab to verify the sub as been added to favorites.
5. Close app
6. Reopen app
7. Open subs tab to see no favorites.

**Expected behavior**
Favorites list should stay between app sessions.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Browser: Firefox Beta
 - Version: v20 beta 8 (Pro)

**Comment by RecklessDwark** [comment] 2020-07-04 13:44
This is intended, the Anonymous mode is not meant to save between sessions

**Comment by geominorai** [comment] 2020-07-04 21:22
> This is intended, the Anonymous mode is not meant to save between sessions

That's moot given that search and view history persists between app sessions even without an account.

**Comment by RecklessDwark** [comment] 2020-07-04 21:33
Search and history are saved locally to the app, favorites and subscriptions are tied to a Reddit account, it's working as intended

**Comment by geominorai** [comment] 2020-07-04 21:57
The v20 beta 5 notes had 
> Logged out users can now fav subs

It sounded like an intended feature but just not fully working.

**Comment by laurencedawson** [comment] 2020-07-21 21:59
It wasn't intended but I added it due to feedback. Closing anyways.

**Closed by laurencedawson** 2020-07-21 21:59 UTC
Labels: bug

**Comment by geominorai** [comment] 2020-07-31 20:38
Thanks for patching this in v20 beta 13!
