### ISSUE TITLE
[BUG] Autobrightness switches to max with certian videos

### ISSUE THREAD

**Issue by Desani** [laurencedawson/sync-for-reddit#1213] opened 2022-05-05 20:44 UTC
**Describe the bug**
While browsing reddit, affects all subreddits, when certain videos play, my screen seems to switch auto-brightness to max while playing the video. If I scroll past the video, the screen returns to normal brightness again. It only happens on specific videos and re-occurs when clicking on the video while in the post comments.

**To Reproduce**
Example Video that causes screen brightness to go on max while browsing:
1. Click on (https://www.reddit.com/r/SteamDeck/comments/uj5hsw/hardware_or_software_issue_all_games_been/)

**Expected behavior**
Screen brightness to not change based on video preview

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android 10 One UI 2.5
 - Browser Samsung Browser
 - Version v22.5.4 (been happening for a few previous versions)

**Comment by Desani** [comment] 2022-05-07 14:04
Here is another example of a video that causes the same issue: 
https://www.reddit.com/r/SteamDeck/comments/uja0bi/quick_question_about_temp_and_usage_thanks/

**Comment by laurencedawson** [comment] 2022-06-14 14:48
This is due to HDR content being played. Technically not a bug...

**Comment by laurencedawson** [comment] 2022-06-14 17:02
Closing this in favour of adding an option:

https://github.com/laurencedawson/sync-for-reddit/issues/1380

**Closed by laurencedawson** 2022-06-14 17:02 UTC
Labels: bug
