### ISSUE TITLE
[BUG] Some images opened in dark mode have inverted colors

### ISSUE THREAD

**Issue by mafrasi2** [laurencedawson/sync-for-reddit#1218] opened 2022-05-06 20:07 UTC
**Describe the bug**
Some images (I think only black and white ones, but I'm not sure) look fine in the preview, but have inverted colors when fully opened while the app is in dark mode.

**To Reproduce**
1. Enable auto-dark mode in reddit sync
2. Enable system dark mode globally
3. Open the image in [post A](https://www.reddit.com/r/OldSchoolCool/comments/uj6se4/jamie_lee_curtis_1980/) or images 1-3 in [post B](https://www.reddit.com/r/blackandwhite2/comments/ugjhyf/continuation_of_my_last_post_screenshots/).

**Screenshots**
* ✅[Post A opened in light mode, all good](https://i.imgur.com/NjUTkpH.jpg)
* ❌[Post A opened in dark mode, inverted colors](https://i.imgur.com/VHcaLPW.jpg)
* ✅[Post B, first image opened in light mode, all good
](https://i.imgur.com/q2PxpOK.jpg)
* ❌[Post B, first image opened in dark mode, inverted colors
](https://i.imgur.com/K0rND7A.jpg)
* ✅[Post B, fourth image opened in dark mode, all good
](https://i.imgur.com/YnJtQlk.jpg)
* ✅[Post B, preview in dark mode, all good](https://i.imgur.com/TnA85H1.jpg)

**Smartphone:**
 - Device: Xiaomi Poco X3 Pro
 - OS: Android 11, MIUI Global 12.5.5
 - Browser: Firefox
 - Version: v22.5.4

**Additional context**
Long pressing the preview brings up a full screen version of the images and there they have correct colors.

As far as I can see, there is no transparency involved here (these are JPEGs after all), so this is not the same as [this non-bug](https://www.reddit.com/r/redditsync/comments/50xma9/bug_this_image_showing_inverted_colors/), but maybe the same as [this bug](https://www.reddit.com/r/bugs/comments/hctbgn/colors_inverted_in_reddit_mobile_dark_mode_when/).

**Comment by laurencedawson** [comment] 2022-06-14 13:22
Unable to reproduce this. Very odd. Closing but I'll re-open if I get another report. Cheers

**Closed by laurencedawson** 2022-06-14 13:22 UTC
Labels: bug
