### ISSUE TITLE
[BUG] Link to video = hard crash. 

### ISSUE THREAD

**Issue by rhamej** [laurencedawson/sync-for-reddit#1376] opened 2022-06-05 15:00 UTC
**Describe the bug**  
Crash to desktop when clicking a link to a reddit video.

**Steps to Reproduce**  
1. Go to https://www.reddit.com/r/Rainmeter/comments/uwvxu2/_/
2. Click on 'video link'
3. See error

**Expected behavior**  
Video to play 

**Smartphone (please complete the following information):**
 - Device: [Pixel 6]
 - Android: [12]
 - Sync version: [v22.5.20]
 - Sync variant: [pro]

**Comment by laurencedawson** [comment] 2022-06-05 18:22
Working fine here. Can you print screen your "link handling" options please.

**Comment by rhamej** [comment] 2022-06-05 18:25
![Screenshot_20220605-132339](https://user-images.githubusercontent.com/1900225/172064980-b7d8e02a-cde9-449b-87a1-1422f8ed0973.png)


This? Is there a way to get a log? I just tried again. Still crashes.

**Comment by laurencedawson** [comment] 2022-06-13 21:41
Got it.

Looks like a duplicate of this:

https://github.com/laurencedawson/sync-for-reddit/issues/1084

**Closed by laurencedawson** 2022-06-13 21:41 UTC
Labels: bug, cant replicate, details neeed
