### ISSUE TITLE
[BUG] Sync shows old subreddit icon

### ISSUE THREAD

**Issue by ronakg** [laurencedawson/sync-for-reddit#1262] opened 2022-05-16 16:08 UTC
**Describe the bug**
A sub I follow recently updated their icon. The app still shows the old icon unless I visit the sub. Even after that, the icon keeps changing back to the old one.

Sub in question: /r/warriors 

**Expected behavior**
Once the app discovers new icon, it should always show the new icon.

**Screenshots**

Before -

![Screenshot_20220516-090904](https://user-images.githubusercontent.com/1058322/168636972-2b7a08e0-dc6c-445f-b6c1-bb00d545ddfa.png)

After -

![Screenshot_20220516-090916](https://user-images.githubusercontent.com/1058322/168636878-923e4669-3277-47bf-961d-b10973b7847a.png)

**Device information**

    Sync version: v22.5.4    
    Sync flavor: free    
    Removed ads: true    
    
    View type: Slides    
    Push enabled: false    
    
    Device: raven    
    Model: Google Pixel 6 Pro    
    Android: 12

**Additional context**

**Comment by rentsmdi** [comment] 2022-05-25 13:34
I found the same bug, the issue is still open!
If you want to merge, @ronakg :)

https://github.com/laurencedawson/sync-for-reddit/issues/1075

**Comment by laurencedawson** [comment] 2022-05-25 13:35
Closing, duplicate:

https://github.com/laurencedawson/sync-for-reddit/issues/1075

**Closed by laurencedawson** 2022-05-25 13:35 UTC
Labels: bug

**Comment by rentsmdi** [comment] 2022-05-27 05:55
Thank you so much @laurencedawson  which version will include this fix?

**Comment by laurencedawson** [comment] 2022-05-27 08:43
I classed as it's a duplicate. It's not fixed
