### ISSUE TITLE
[BUG] Issue with comments in Sports Mode

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1168] opened 2022-04-29 12:08 UTC
**Spotted on**
https://www.reddit.com/r/redditsync/comments/udggez

**Comment by thereddestdog** [comment] 2022-04-29 16:01
Duplicate of a comment in #356 FYI

**Comment by laurencedawson** [comment] 2022-05-03 11:43
Closing. Duplicate.

**Closed by laurencedawson** 2022-05-03 11:43 UTC
Labels: bug
