### ISSUE TITLE
[BUG] Double tap and slide to zoom in videos toggles the control bar

### ISSUE THREAD

**Issue by TiboQc** [laurencedawson/sync-for-reddit#229] opened 2020-06-10 12:20 UTC
**Describe the bug**
Using the double-tap-hold-and-slide to zoom in and out of videos ends up toggling the video control bar (disappears the first time you zoom enough, reappears when you zoom out and in again, etc.).

**To Reproduce**
1. First you need to allow zooming in videos from the settings.
1. Find a gif or video, clock once to open them, then do a double-tap and keep pressing on the second tap. This allows you to zoom in and out while allowing down and up.
1. If you zoom in enough, the bottom control bar (with the play/pause, mute and timeline) will disappear. If you repeat, it will make it reappear.

**Expected behavior**
Zoning in on videos using that method should not hide or toggle the video control bar.

**Screenshots**
![Screenshot_20200610-081459](https://user-images.githubusercontent.com/287598/84266748-fb1cd600-aaf2-11ea-8127-dfbdfbdff428.png)
![Screenshot_20200610-081507](https://user-images.githubusercontent.com/287598/84266756-feb05d00-aaf2-11ea-9e6d-84ef166723f3.png)

**Smartphone (please complete the following information):**
 - Device: LG V30
 - OS: Android 9
 - Browser Sync for Reddit Pro
 - Version vv20 beta 4

**Additional context**

**Comment by laurencedawson** [comment] 2021-01-15 18:13
Closing as this is intended behaviour. I plan on redesigning this after v20 goes live too.

**Closed by laurencedawson** 2021-01-15 18:13 UTC
Labels: bug, wontfix

**Comment by TiboQc** [comment] 2021-01-15 21:41
Yeah I realized it was caused by the long press on screen (which is a really good feature). The behavior, though weird, is acceptable.

**Comment by Nxt3** [comment] 2022-05-31 00:04
Any chance of revisiting this? I came here to post the same issue but never realized long-pressing on a photo hides the control bar.
