### ISSUE TITLE
[bug] list view youtu.be type indicator

### ISSUE THREAD

**Issue by co5mo** [laurencedawson/sync-for-reddit#1062] opened 2022-04-13 21:32 UTC
hi

list view type indicator for domain youtu.be is picture not video

thanks

**Comment by bohrabhijeet** [comment] 2022-04-14 03:58
This is a duplicate of https://github.com/laurencedawson/sync-for-reddit/issues/1062

**Comment by bohrabhijeet** [comment] 2022-04-14 03:59
This is a duplicate of https://github.com/laurencedawson/sync-for-reddit/issues/1029

**Closed** 2022-04-14 11:10 UTC
