### ISSUE TITLE
[BUG] Jumps back to the top when viewing tall images

### ISSUE THREAD

**Issue by felimenta970** [laurencedawson/sync-for-reddit#359] opened 2020-09-03 18:00 UTC
**Describe the bug**
When reading posts like this one (https://i.redd.it/jv616i8ybdk51.png), where you have to scroll through the image to read it, the view will occasionally jump back up to the top of the image. It happened 3 or 4 times while reading that post.

**To Reproduce**
1. Open image that is taller than the screen
2. Scroll down the image
3. Wait

**Screenshots**

**Smartphone (please complete the following information):**
Samsung Galaxy S8+ Android 9 Sync Pro v20(beta 16)

**Additional context**
Reported here: https://www.reddit.com/r/redditsync/comments/ik8vzu/bug_when_viewing_tall_images_the_view_jumps_back/g3tifhb/?context=3

**Comment by laurencedawson** [comment] 2021-01-15 04:11
Unable to reproduce. CLosing.

**Closed by laurencedawson** 2021-01-15 04:11 UTC
Labels: bug
