### ISSUE TITLE
[BUG] Comment videos glitch when you open the app in multi window

### ISSUE THREAD

**Issue by Entetty** [laurencedawson/sync-for-reddit#941] opened 2022-03-28 23:09 UTC
**Describe the bug**
Comment videos will shrink and go back to the original size really quickly when multi window is started

**To Reproduce**
1. Go to thread with comments that have videos
2. Put the app in multi window mode
3. Videos will start glitching

**Expected behavior**
For the videos to stay the same size

**Screenshots**

https://user-images.githubusercontent.com/102560467/160501187-06134bb1-aa2f-4e68-a9c1-9060fe5486b3.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung note 20
 - OS: Android 12
 - Browser: samsung internet 
 - Version: 22.3.24

**Comment by laurencedawson** [comment] 2022-03-29 22:13
I really hate multi window...

**Comment by laurencedawson** [comment] 2022-04-22 17:45
Unable to reproduce. Closing for now.

**Closed by laurencedawson** 2022-04-22 17:45 UTC
Labels: bug
