### ISSUE TITLE
[BUG] Error loading page 90% of the time

### ISSUE THREAD

**Issue by segfault23** [laurencedawson/sync-for-reddit#944] opened 2022-03-29 09:40 UTC
**Describe the bug**
I've been having an issue the past couple months that makes the app unusable for the most part.

When loading posts, comments, profiles, anything, 90% of the time I get "Error loading page". I'm not the only one who has had this issue, too:

- https://www.reddit.com/r/redditsync/comments/qzpixi/error_loading_page_400_for_about_3_days_now/
- https://www.reddit.com/r/redditsync/comments/nh9giz/bug_error_loading_page_issue/
- https://www.reddit.com/r/redditsync/comments/nqocdo/error_loading_page/
- https://www.reddit.com/r/redditsync/comments/ppkn3y/error_loading_page/

The issue stops when using the Anonymous profile, however, I'd prefer not to have to do that.

**To Reproduce**
1. Go to any page on the app (frontpage, subreddit xyz, comments, profile, etc)
2. 10% of the time, the app works long enough. I can do everything normally. Then, if I set the phone aside for a while, or sometimes even randomly while using the app, it'll fail
3. See error

**Expected behavior**
The posts should load properly

**Screenshots**
![Screenshot_20220323-001523](https://user-images.githubusercontent.com/100366198/160582445-f655a1a0-8947-4bfd-928d-0b923278ca4f.jpg)
![Screenshot_20220325-135014](https://user-images.githubusercontent.com/100366198/160582474-8ca69579-7c85-4458-952f-c3298ffb6bca.jpg)

**Smartphone:**
**Device information**

    Sync version: v22.3.21    
    Sync flavor: pro    
    
    View type: Slides    
    Push enabled: false    
    
    Device: OnePlus7Pro    
    Model: OnePlus GM1917    
    Android: 11

**Additional context**
N/A

**Comment by laurencedawson** [comment] 2022-03-29 10:48
The error reported is from Reddit directly.

You're going over their rate limit with is pretty insane.

**Comment by segfault23** [comment] 2022-03-29 13:50
I unfortunately am not doing anything other than opening the app once lol

I wish I could refresh that many times!

**Comment by laurencedawson** [comment] 2022-03-29 14:12
The links you posted had different error messages

Yours is for a very specific issue. Could you try disabling message
checking?

**Comment by segfault23** [comment] 2022-03-29 14:24
My original links were indeed incorrect. I had one in there that was an SSL error, but I've since removed it. I've edited it to have all links that I believe are the same issue.

I've disabled message checking (was set at 60min). Will see if that has any effect. Fortunately, the app is working right now, but I have low hopes of it continuing.

Thanks for the prompt responses! I love the app, hope to help you come to a fix for this issue :)

**Comment by laurencedawson** [comment] 2022-03-29 14:42
I'll keep an eye on this. Can't reproduce it my end at the moment...

**Comment by segfault23** [comment] 2022-04-14 16:54
Hey Laurence,

I've done a bit of debugging and do think it has something to do with my ISP. When on VPN, the authentication call at the start of browsing seems to succeed (after swapping profiles).

[I've made a short video of the behavior here](https://youtube.com/shorts/85TETCyP3s0) (Sorry it's a short, can't figure out how to upload without creating one).

I believe it has something to do with the initial authentication call conflicting with Virgin Media for some reason. It does not happen with anonymous, nor after I've connected to VPN.

However, I'm thinking the app still has a bug because every other application works, and the (horrible app, IMO) Relay pro app works fine despite my ISP.

Hope this helps, even slightly!

**Comment by laurencedawson** [comment] 2022-04-22 18:07
I wonder if for some reason they're returning rate limiting values for the whole ISP...

**Comment by mheppner** [comment] 2022-05-18 20:28
I've been having the same issue as well for quite some time. It was even happening on v19 to the point where I stopped using Sync. I can't find a pattern with it - wifi vs 5G, signed-in vs anonymous, using different profiles, etc.

I can switch over to other apps (I'm using Infinity now) using the same profile and use the account flawlessly. In Sync, I can be scrolling through posts, put my phone down and come back hours later, click on a post, then get the rate limiting message. I really don't think it's rate limiting coming from Reddit's APIs.

I'm currently locked out in Sync with the rate limiting message, refreshing does nothing. But I can use Infinity just fine. I'm connected to PiHole and can see the DNS requests going through. Screenshot below shows the DNS requests only from Sync leading up to the error message.

There are a lot more users experiencing this too, more details can be found on [reddit](https://old.reddit.com/r/redditsync/search?q=rate+limit&restrict_sr=on&sort=relevance&t=all).
 
<img width="450" alt="Screen Shot 2022-05-18 at 4 24 12 PM" src="https://user-images.githubusercontent.com/2390428/169149750-36b58dfa-adc3-4c76-8181-a77731a39e81.png">


```
Sync version: v22.5.18
Sync flavor: pro     

Device: Google Pixel    
Model: Pixel 6 
Android: 12
```

**Comment by laurencedawson** [comment] 2022-06-07 21:52
I'm only displaying what the headers are saying. 

Every time this issue has come up it's been down to bloody ISPs messing things up.

Switching to a VPN or enabling DNS over HTTPS seems to fix the issue. Closing for now.

**Closed by laurencedawson** 2022-06-07 21:52 UTC
Labels: bug, wontfix, cant replicate
