### ISSUE TITLE
[BUG] Artifacts on comments

### ISSUE THREAD

**Issue by rafaeldamasceno** [laurencedawson/sync-for-reddit#453] opened 2020-12-10 15:05 UTC
**Describe the bug**
Sometimes, comments will have rendering artifacts in their text.

**To Reproduce**
1. Go any post's comments
2. Scroll down until you see a comment with artifacts

**Expected behavior**
The comment text shouldn't have any artifacts.

**Screenshots**
The artifacts can be seen on the lower parent comment, specially in the higher parts of the characters.
![Screenshot_20201210-011750_Sync_Pro](https://user-images.githubusercontent.com/6492427/101789062-bb15ca80-3af8-11eb-9b77-c3088bb2000c.png)

**Device information**

    Sync version: v20 (beta 26)    
    Sync flavor: pro    
    
    View type: Small cards    
    Push enabled: true    
    
    Device: beryllium    
    Model: Xiaomi POCO F1    
    Android: 10

**Additional context**
If you collapse and expand the comment, the artifacts go away.

**Comment by laurencedawson** [comment] 2021-01-15 20:34
Unable to reproduce this. I would suggest changing the font. 

Closing for now but if that doesn't help let me know.

**Closed by laurencedawson** 2021-01-15 20:34 UTC
Labels: bug

**Comment by rafaeldamasceno** [comment] 2021-02-13 13:04
![Screenshot_20210213-130152_Sync_Pro](https://user-images.githubusercontent.com/6492427/107850643-d6080200-6dfb-11eb-85d5-2c13f066ebcc.png)

Still happening from time to time...

**Device information**

    Sync version: v20 (beta 32)    
    Sync flavor: pro    
    
    View type: Small cards    
    Push enabled: true    
    
    Device: beryllium    
    Model: Xiaomi POCO F1    
    Android: 10

**Comment by laurencedawson** [comment] 2021-02-13 15:15
Did you try changing the comment font?
