### ISSUE TITLE
[BUG] "Long press selftext to select text" only works in frontpage, not after that post is opened

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/sync-for-reddit#278] opened 2020-06-27 17:04 UTC
Option is enabled - https://www.imgur.com/a/jGBNm3u

**Comment by geominorai** [comment] 2020-07-12 08:21
Duplicate of #268.

**Comment by laurencedawson** [comment] 2020-09-08 16:22
Closing duplicate.

**Closed by laurencedawson** 2020-09-08 16:22 UTC
