### ISSUE TITLE
[BUG] Comments don't animate in when posts have few comments

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/sync-for-reddit#312] opened 2020-07-20 00:23 UTC
When opening posts with few comments (usually below 10), the comments won't animate in at all.

**Comment by laurencedawson** [comment] 2020-07-21 11:38
Unable to reproduce this. Any chance of a screen recording?

**Comment by Nxt3** [comment] 2020-07-21 11:51
https://photos.app.goo.gl/g2pDjAiE14fGUEe86

Sure thing

**Comment by laurencedawson** [comment] 2021-01-15 04:07
Unable to reproduce. CLosing for now,

**Closed by laurencedawson** 2021-01-15 04:07 UTC
Labels: bug, cant replicate

**Comment by Nxt3** [comment] 2021-01-19 02:21
[This is still happening on v20 (beta 28)](https://photos.app.goo.gl/apHAjCWqamLk3ZXL9).

These are my card settings if that helps:

![Screenshot_20210118-201905.png](https://user-images.githubusercontent.com/2940826/104979783-1cbc3500-59d3-11eb-8ac2-e505e3022ced.png)

![Screenshot_20210118-201914.png](https://user-images.githubusercontent.com/2940826/104979795-2180e900-59d3-11eb-8521-03db757c6390.png)
