### ISSUE TITLE
[BUG] v20 Beta 11: After switching accounts, the favorited subs list doesn't reset, and the original account's favorites appear in addition to the second account's favorites

### ISSUE THREAD

**Issue by mbestavros** [laurencedawson/sync-for-reddit#313] opened 2020-07-21 01:30 UTC
**Describe the bug**
After switching to a new (logged-in) account from the default (also logged-in) account, the favorited subreddit list (at the top of the "Subs" menu) includes favorites from both the original account and the new one, with the second account's favorites appended to the original.

**To Reproduce**
1. Use Sync as normal, with default signed-in account. Open the Subs list. At the top, observe a set of favorited subreddits (example below):

```
acc1-fav1
acc1-fav2
acc1-fav3
```

2. Use the top bar account switcher to switch to a second, signed in account.
3. Open the Subs list. At the top, observe a set of favorited subreddits that incorrectly includes the previous account's favorites (example below):

```
acc1-fav1
acc1-fav2
acc1-fav3
acc2-fav1
acc2-fav2
acc2-fav3
```

**Expected behavior**
When performing step 3 above, I should see only the second account's favorites (example below):

```
acc2-fav1
acc2-fav2
acc2-fav3
```

**Smartphone (please complete the following information):**
 - Device: Pixel 1 XL
 - OS: Android 10
 - Browser: Chrome
 - Version: 20 beta 11

**Comment by laurencedawson** [comment] 2020-07-21 11:37
Tried a few times but I'm unable to reproduce this...

Does it happen every time?

**Comment by mbestavros** [comment] 2020-07-21 14:40
@laurencedawson Yes. Every time I switch accounts from the main one (which appears correctly), the favorites list includes the favorites from both the main account and the one I just switched to. Happens every time.

**Comment by thereddestdog** [comment] 2020-07-27 13:10
I had this issue. I ended up resetting all app data to correct it

**Comment by mbestavros** [comment] 2020-07-27 23:18
I've just updated to Beta 12, and I'm still seeing this issue.

**Comment by mbestavros** [comment] 2020-08-13 22:57
Just checking in to say that it is still present on Beta 13. I have not tried resetting app data yet, but I may. Will update if that fixes things.

**Comment by laurencedawson** [comment] 2020-09-08 15:53
Just checking in on this issue. I think this has since been fixed so closing but let me know if you're still seeing it and I'll re-open.

**Comment by mbestavros** [comment] 2020-09-08 16:05
@laurencedawson I am indeed still seeing the bug on Beta 18. Is there a newer build out that should resolve this?

**Comment by laurencedawson** [comment] 2020-09-08 17:47
Nah 18 is the currently live. Honestly this is very strange as I cant reproduce this at all.

Is it possible for you to try reinstalling and seeing if this issue persists?

**Comment by thereddestdog** [comment] 2020-09-08 17:56
He needs to clear app data/storage and it will be fixed

**Comment by mbestavros** [comment] 2020-09-08 18:32
@laurencedawson I just did as @thereddestdog suggested, and it is still broken, believe it or not. I see my primary account's favorites in addition to the second account's.

I will try reinstalling as a last resort, but this appears to be persistent across installs for me.

**Comment by mbestavros** [comment] 2020-09-08 18:43
@laurencedawson Here's something strange: I manually removed every account from Sync, cleared cache and app data, uninstalled, and reinstalled. However, when I open the app, my old accounts (the same ones I manually removed before uninstalling) were still there.

Could this be some kind of stale database from an earlier version of the app? I've been using Sync beta continuously since the first v20 betas (not the alphas).

**Comment by laurencedawson** [comment] 2020-09-11 12:56
Man I have no idea what is going on there. Clearing the app data should be enough, let alone reinstalling. All app data should be removed by android when you uninstall...

**Comment by mbestavros** [comment] 2020-09-11 13:46
You'd think so, right?

I'd imagine a factory reset would do the trick, but I'm not keen on doing that on my primary device. Guess I'll just have to wait until I upgrade (I'm eyeing the new 5G Pixels)...

**Comment by laurencedawson** [comment] 2020-09-17 14:16
Keep me posted, interested to figure this one out.

**Comment by mbestavros** [comment] 2020-09-17 14:25
Will do!

**Comment by mbestavros** [comment] 2020-11-24 22:33
@laurencedawson I have an update (I think)!

I just got my new Pixel yesterday, and have set up Sync beta with it. First pass, when I logged into my secondary account, things seemed to work as expected! Each account's favorites were segregated, as they should be.

However, *as soon as I restored a settings backup from my primary account*, the bug appeared, which leads me to believe it's related to backup/restore. Hopefully a lead for you :smile:

**Comment by mbestavros** [comment] 2020-12-06 04:58
@laurencedawson I did some tinkering tonight and can further confirm that the above was indeed the issue. Previously, I was restoring an old app settings backup on top of my newly logged-in accounts, and that ended up reproducing this bug. The backup in question is at least several months old, and I assume it was created from the profile containing my primary account.

This time, after resetting the app, I recreated my settings manually while _not_ logged into any specific account and saved it. Sure enough, when I restored _that_ backup on top of my accounts, the favorites bug didn't appear -- **everything worked as expected.**. So the backup/restore functionality is somehow the culprit -- whether it's the actual backup file itself or the code to restore backups, I'm not sure, but it sure seems like it has to be here.

**Comment by laurencedawson** [comment] 2020-12-08 18:53
Aha I guess this isn't a bug then.

In sync you can have local favourites and restoring your backup would keep your old ones locally. You can however go to the three dots (top left of the drawer) and hit reset favourites!

**Comment by mbestavros** [comment] 2020-12-08 18:58
Thanks for the clarification! I did not know about that functionality at all.

I still find it a bit peculiar that my account's favorites were somehow saved as local favorites, though. I don't recall taking any particular action to save anything as a local favorite.

**Comment by laurencedawson** [comment] 2021-02-06 00:03
Re-opening as another user is reporting this issue:

https://www.reddit.com/r/redditsync/comments/lddxso/bug_favorites_shown_from_other_profiles/

**Comment by laurencedawson** [comment] 2021-02-19 02:34
Added an additional fix.

**Closed by laurencedawson** 2021-02-19 02:34 UTC
Labels: bug, cant replicate, details neeed
