### ISSUE TITLE
A volume mode navigation for browsing posts. 

### ISSUE THREAD

**Issue by hungrypippo** [laurencedawson/sync-for-reddit#1102] opened 2022-04-21 07:30 UTC
A simple volume key navigation for browsing reddit posts. 

Volume + will scroll down and a volume - will scroll up, this could be had with an option where the user can select to flip what the volume + and volume - does. 

Sometimes when my other hand is busy holding some bags and i am on a public transport, a volume key navigation is really really helpful. As with this i can grip the phone properly and still browse the posts. And this is specially for someone who has small hands and uses a large screen device. 

This could be also paired up with samsung note device's S-pen, where in a click of the s-pen button will help me scroll through the posts.

**Comment by bohrabhijeet** [comment] 2022-04-21 07:33
This is a duplicate of https://github.com/laurencedawson/sync-for-reddit/issues/1096
Pro tip: Please go through the issues before adding yours. :)

**Comment by hungrypippo** [comment] 2022-04-21 07:38
Oh thanks. I didnt see that.

**Closed** 2022-04-21 10:11 UTC
Labels: enhancement
