### ISSUE TITLE
Screenshot share of comments.

### ISSUE THREAD

**Issue by hungrypippo** [laurencedawson/sync-for-reddit#1104] opened 2022-04-21 07:37 UTC
Sync already has a feature of sharing a post with the help of screenshot. 

Would be nice if i could share a post with parent comment and even child comment (when needed) with the help of screenshot.

**Comment by bohrabhijeet** [comment] 2022-04-25 19:10
Duplicate of https://github.com/laurencedawson/sync-for-reddit/issues/513

**Closed** 2022-04-25 19:12 UTC
Labels: enhancement
